# Generated by Django 4.1 on 2022-08-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='d_of_b',
            new_name='dob',
        ),
    ]
